#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    appname: cloud-service
    lease-renewal-interval-in-seconds: 1

server:
  port: 8071

spring:
  application:
    name: cloud-service


